module.exports = {
    TODO_ADD: 'TODO_ADD',
    TODO_TOGGLE: 'TODO_TOGGLE',
    TODO_REMOVE: 'TODO_REMOVE',

    ROUTE_NAVIGATE: 'ROUTE_NAVIGATE',

    ROUTE_DEFAULT: 'todos',
    ROUTE_TODOS: 'todos',
    ROUTE_HELP: 'help',
    ROUTE_FLICKR: 'flickr',

    NOTIFY_HIDE: 'NOTIFY_HIDE',

    FLICKR_FIND: 'FLICKR_FIND',
    FLICKR_FIND_SUCCESS: 'FLICKR_FIND_SUCCESS',
    FLICKR_FIND_FAIL: 'FLICKR_FIND_FAIL'
};
