module.exports = {
    ROUTE_TODOS: 'ROUTE_TODOS',
    ROUTE_HELP: 'ROUTE_HELP',
    ROUTE_FLICKR: 'ROUTE_FLICKR',
    ROUTE_DEFAULT: 'ROUTE_TODOS',   // default route!

    ROUTE_NAVIGATE: 'ROUTE_NAVIGATE',

    TODO_ADD: 'TODO_ADD',
    TODO_TOGGLE: 'TODO_TOGGLE',
    TODO_REMOVE: 'TODO_REMOVE',

    NOTIFY_HIDE: 'NOTIFY_HIDE',

    FLICKR_FIND: 'FLICKR_FIND',
    FLICKR_FIND_SUCCESS: 'FLICKR_FIND_SUCCESS',
    FLICKR_FIND_FAIL: 'FLICKR_FIND_FAIL'
};
